{
 "title": "Kafka Monitoring",
 "tags": [
  "kafka",
  "monitoring",
  "performance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Оборудование", "type": "row" },
  {
   "title": "График нагрузки процессора",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Load - {{instance}}"
    }
   ]
  },
  {
   "title": "Текущая нагрузка процессора",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "График нагрузки диска",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "Disk Usage - {{instance}}"
    }
   ]
  },
  {
   "title": "График нагрузки ОЗУ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "RAM Usage - {{instance}}"
    }
   ]
  },
  {
   "title": "Текущая нагрузка ОЗУ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Компоненты кластера Kafka", "type": "row" },
  {
   "title": "Доступность кластера",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions",
     "legendFormat": "Under Replicated Partitions"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 20 },
   "targets": [
    { "expr": "jvm_threads_state", "legendFormat": "{{state}} - {{instance}}" }
   ]
  },
  {
   "title": "Request Total Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Кол-во текущих подключений",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_connection_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_partitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Broker Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Queue Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Producer Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedproducerrequests_total[5m])",
     "legendFormat": "{{topic}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Очереди", "type": "row" },
  {
   "title": "Размер очереди",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_log_logendoffset - kafka_log_logstartoffset",
     "legendFormat": "{{topic}} - {{partition}}"
    }
   ]
  },
  {
   "title": "Кол-во partition per topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "count by (topic) (kafka_log_logendoffset)"
    }
   ]
  },
  {
   "title": "Динамика лага",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 18, "y": 36 },
   "targets": [
    { "expr": "kafka_consumer_group_max_lag", "legendFormat": "{{group}} - {{topic}}" }
   ]
  },
  {
   "title": "Очереди без сообщений за последний 24 часа",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kafka_log_logendoffset - kafka_log_logstartoffset"
    }
   ]
  },
  {
   "title": "Кол-во consumer per topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "count by (topic) (kafka_consumer_group_members)"
    }
   ]
  },
  {
   "title": "Общее состояние лага",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "max(kafka_consumer_group_max_lag)",
     "legendFormat": "Max Lag"
    }
   ]
  },
  { "title": "Consumer", "type": "row" },
  {
   "title": "Bytes Consumed Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_metrics_bytes_consumed_total[5m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Rebalance Time Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "kafka_consumer_group_rebalance_time_max",
     "legendFormat": "{{group}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Скорость обработки сообщений",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_metrics_records_consumed_total[5m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Доступность",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "up{job=\"kafka\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Динамика балансировки",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 18, "y": 52 },
   "targets": [
    {
     "expr": "kafka_consumer_group_rebalance_rate",
     "legendFormat": "{{group}} - {{instance}}"
    }
   ]
  }
 ]
}